### ISSUE TITLE
Provide support for aliased and chained join fetches

### ISSUE THREAD

**Issue by lukasj** [eclipse-ee4j/jpa-api#28]
In JPA 2, JPQL does not support an alias on a JOIN FETCH and subsequently these join fetches can not be chained.

E.g.

```
SELECT
    _user
FROM
    User _user
        LEFT JOIN FETCH
    user.address _address
        LEFT JOIN FETCH
    _address.city _city
```

Several persistence providers, like Hibernate and the JPA reference implementation EclipseLink do support this syntax (see e.g. [http://java-persistence-performance.blogspot.com/2012/05/jpql-vs-sql-have-both-with-eclipselink.html](http://java-persistence-performance.blogspot.com/2012/05/jpql-vs-sql-have-both-with-eclipselink.html))

To improve portability, I would like to propose to standardize support for aliased and chained join fetches.

**Comment by AleksNo** [comment]
Mhhh, maybe it is a good idea to standardize it. On reddit, they brag about it:
https://www.reddit.com/r/java/comments/1cztu3z/comment/l66jsy9/

And EclipseLink and Hibernate already support it. So it would be a pretty lowhanging fruit.

**Comment by beikov** [comment]
EntityGraphs is the tool for specifying what you want to fetch. 
Allowing aliasing would only make sense and be safe for singular associations. If a plural association join fetch alias would be filtered, that could lead to data loss when flushing data back, which is why the JPA spec probably disallowed this in the first place.
If you are looking for a way to filter collections, then we'd need something like Hibernate ORM filters in JPA.
I'm not against specifying this, but I'd make it clear that this is limited to singular associations.
