### ISSUE TITLE
Add support for EL expressions in JPA-QL and native queries.

### ISSUE THREAD

**Issue by lukasj** [eclipse-ee4j/jpa-api#84]
This proposal suggests adding support using [EL expressions](http://docs.oracle.com/javaee/7/tutorial/doc/jsf-el002.htm) in JPA query strings. With this one could define query string templates and dynamic parameter bindings based on EL (Expression Language).

*   Immediate evaluation (via $ {...}) could be used to statically alter the query string in cases where the user
    wants to statically generate a fixed part of a query. This could be used to add query fragments or adjust the name
    of tables or columns / fields.
    - Deferred evaluation (via #{...}

    ) could be used to dynamically compute a parameter value in cases where the user
    wants to avoid having to compute and set the parameter values explicitly.

## <a name="Example1"></a>Example 1

The JPA-QL query:

```
select o from BusinessObject o where o.owner.emailAddress like ?#{hasRole('ROLE_ADMIN') ? '%' : principal.emailAddress}
```

would translate to:

```
select o from BusinessObject o where o.owner.emailAddress like ?1
```

With ?1 bound to the result of the dynamically evaluated EL expression <tt>hasRole('ROLE_ADMIN') ? '%' : principal.emailAddress</tt>. The parameter ?1 would be dynamically registered.

## <a name="Example2"></a>Example 2

The JPA-QL query:

```
select o from BusinessObject o where o.owner.emailAddress = ?1 ${ currentTenant != null ? ' and o.tenant = ?#{' + currentTenant.id + '}' : ''}
```

would translate to either:

```
select o from BusinessObject o where o.owner.emailAddress = ?1
```

or:

```
select o from BusinessObject o where o.owner.emailAddress = ?1 and o.tenant = ?2
```

where ?2 is bound to the result of the dynamically evaluated expression "currentTenant.id".

It would be helpful to have some kind of SPI at the EntityManagerFactory that allows libraries or users to customize the EL expression context somehow, e.g. by allowing to expose functions, properties, variables and the like.

### <a name="javax.el.ExpressionasJPAQueryparametervalues"></a>javax.el.Expression as JPA Query parameter values

As an extension one could also allow to bind parameter values of type <tt>javax.el.Expression</tt> to every exposed parameter of a JPA query. The value to be bound could then derived at query time by evaluating the given expression. We implemented that feature in the latest version of the [Spring Data JPA Repository abstraction](https://spring.io/blog/2014/07/15/spel-support-in-spring-data-jpa-query-definitions).

**Comment by gavinking** [comment]
I'm really not a fan of this idea at all. The given code examples are kind of a dogs breakfast of an expression language embedded via `{...}` quotes in a QL embedded via `"..."` quotes in typesafe Java code.

While the embedding of HQL queries in Java is bearable and justifiable on the basis that the same logic would otherwise probably occur in embedded SQL, or in SQL scripts that aren't typechecked until runtime, it seems to me that the additional loss of typesafety implied by shifting expressions that currently occur in typesafe Java code into a _second level_ of embedding is much harder to justify.

Worse, it makes it even harder for tools to add typechecking to embedded HQL, which is currently tricky but possible.

Also, I'm not certain about this, but it seems to me that the use of EL the modern web APIs is increasingly uncommon. Perhaps someone can correct me if I'm wrong on that.

**Comment by gavinking** [comment]
I propose we close this.

**Comment by gavinking** [comment]
> I propose we close this.

Please someone speak up if you think I should not! :-)
